### ISSUE TITLE
ReferenceError: headers is not defined in algorithmia/lib/data.js

### ISSUE THREAD

**Issue by loretoparisi** [algorithmiaio/algorithmia-nodejs#5]
While doing the algorithm `DeepFilter`

```node
var client = algorithmia(process.env.ALGORITHMIA_API_KEY);
var input={ images: [ 'https://en.wikipedia.org/wiki/Nikola_Tesla#/media/File:N.Tesla.JPG' ],
  savePaths: [ 'data://.my/DeepFilterTest/stylized_image.jpg' ],
  filterName: 'space_pizza' }
client.dir('data://.my/DeepFilterTest/').create((res)=>console.log(res))
```

I get

```
ReferenceError: headers is not defined
    at Dir.create (/myProject/node_modules/algorithmia/lib/data.js:135:100)
    at repl:1:32
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInContext (vm.js:31:12)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:489:10)
    at emitOne (events.js:101:20)
```

**Comment by jamesatha** [comment]
Thanks for letting us know that this was an issue. The latest version (which was just published) has the fix.

**Comment by loretoparisi** [comment]
@jamesatha was related to `node` only or affected `python` as well?
Thanks for the fix.

**Comment by jamesatha** [comment]
This was only an issue in the nodejs client
